name: psychologist-bot

services:
  # Сервис MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - psychologist_bot_network
    restart: always

  # Телеграм бот
  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - psychologist_bot_network
    restart: always

networks:
  psychologist_bot_network:
    driver: bridge

volumes:
  mongodb_data: 